name: CI/CD Pipeline # Имя Workflow, отображается на вкладке Actions

on: # События, которые запускают Workflow
  push: # Триггер при пуше
    branches:
      - master # Запуск только при пуше в ветку master
  pull_request: # Триггер при создании Pull Request

jobs:
  build: # Job для сборки приложения
    name: Build # Имя Job'а
    runs-on: ${{ matrix.os }} # Виртуальная машина, на которой запускается Job (определяется из матрицы)
    strategy:
      matrix: # Матрица для параллельного выполнения на разных ОС
        os: [ubuntu-latest, windows-latest, macos-latest] # ОС: Ubuntu, Windows, macOS

    steps: # Шаги для выполнения Job'а
      - name: Checkout code # Шаг для клонирования кода репозитория
        uses: actions/checkout@v3 # Экшен для клонирования

      - name: Setup Go # Шаг для установки Go
        uses: actions/setup-go@v4 # Экшен для настройки окружения Go
        with:
          go-version: 1.23 # Версия Go, которая будет установлена

      - name: Install dependencies # Шаг для установки зависимостей
        run: go mod tidy # Установка и обновление зависимостей

      - name: Build application # Шаг для сборки приложения
        run: go build -o my-go-app . # Компиляция и вывод бинарного файла

  test: # Job для тестирования приложения
    name: Test # Имя Job'а
    runs-on: ${{ matrix.os }} # Виртуальная машина, на которой запускается Job
    needs: build # Тестирование зависит от успешного выполнения Job build
    strategy:
      matrix: # Матрица для выполнения тестов на нескольких ОС
        os: [ubuntu-latest, windows-latest, macos-latest] # ОС: Ubuntu, Windows, macOS

    steps: # Шаги для выполнения Job'а
      - name: Checkout code # Шаг для клонирования кода репозитория
        uses: actions/checkout@v3 # Экшен для клонирования

      - name: Setup Go # Шаг для установки Go
        uses: actions/setup-go@v4 # Экшен для настройки окружения Go
        with:
          go-version: 1.23 # Версия Go, которая будет установлена

      - name: Install dependencies # Шаг для установки зависимостей
        run: go mod tidy # Установка и обновление зависимостей

      - name: Run tests # Шаг для запуска тестов
        run: go test ./... # Запуск всех тестов в проекте

  deploy: # Job для деплоя приложения
    name: Deploy # Имя Job'а
    runs-on: ubuntu-latest # Виртуальная машина для выполнения Job'а (Ubuntu)
    needs: [build, test] # Зависимость от успешного выполнения Job'ов build и test
    if: github.ref == 'refs/heads/master' # Условие: деплой выполняется только при пуше в ветку master

    steps: # Шаги для выполнения Job'а
      - name: Checkout code # Шаг для клонирования кода репозитория
        uses: actions/checkout@v3 # Экшен для клонирования

      - name: Print deploy step # Место для добавления шага деплоя
        run: echo "Deployment step executed." # Тестовый шаг, который выводит сообщение
